### PR TITLE
Add sharness tests

### PR DESCRIPTION
**Pull request by chriscool**
I had to add the following change to build multihash:

```
diff --git a/sum.go b/sum.go
index 38c0749..8c71df8 100644
--- a/sum.go
+++ b/sum.go
@@ -64,7 +64,7 @@ func sumSHA512(data []byte) []byte {
 }
 
 func sumSHA3(data []byte) ([]byte, error) {
-       h := sha3.New512()
+       h := sha3.NewKeccak512()
        if _, err := h.Write(data); err != nil {
                return nil, err
        }
```

but I saw that it would go against a patch made recently by @whyrusleeping, so this is not included in this PR.

### CODE REVIEW

**Comment by jbenet** [comment]
thanks @chriscool ! this is perfect.

btw on the build err, maybe you have an old package? https://godoc.org/golang.org/x/crypto/sha3 says the new interface is `sha3.New512`. i sometimes forget to `go get -u golang.org/x/crypto/sha3`

**Comment by whyrusleeping** [comment]
@chriscool youll need to update your go installation, you have an older version

**Comment by jbenet** [comment]
We should see them running on https://travis-ci.org/jbenet/go-multihash/builds/46663508 in a sec

**Comment by chriscool** [comment]
@whyrusleeping my go version is:

go version go1.3.3 linux/amd64

do I need to upgrade to go 1.4 and should it be stated on the README?

@jbenet ok, I will try to `go get -u golang.org/x/crypto/sha3`

Thanks both!

**Comment by jbenet** [comment]
@chriscool it worked! https://travis-ci.org/jbenet/go-multihash/jobs/46663509 :heart: :+1:

**Comment by chriscool** [comment]
Great that it works!
`go get -u golang.org/x/crypto/sha3` is not enough to make it build here.

**Pull request merged**
